# Generated by Django 2.0.1 on 2019-03-04 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping_app', '0002_auto_20190304_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttag',
            name='url_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrapping_app.Urls'),
        ),
        migrations.AlterField(
            model_name='urls',
            name='name',
            field=models.URLField(max_length=255),
        ),
    ]
