# Generated by Django 2.0.1 on 2019-03-04 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping_app', '0003_auto_20190304_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttag',
            name='url_id',
        ),
    ]
