# Generated by Django 2.0.1 on 2019-03-04 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping_app', '0004_remove_producttag_url_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urls',
            name='name',
        ),
        migrations.AddField(
            model_name='producttag',
            name='url',
            field=models.URLField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urls',
            name='url_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrapping_app.ProductTag'),
        ),
    ]
