# Generated by Django 2.0.1 on 2019-03-05 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping_app', '0005_auto_20190304_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urls',
            name='url_id',
        ),
        migrations.DeleteModel(
            name='Urls',
        ),
    ]
