# Generated by Django 2.0.1 on 2019-03-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping_app', '0006_auto_20190305_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttag',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='price',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='size',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
