# Generated by Django 2.0.1 on 2019-03-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping_app', '0007_auto_20190305_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttag',
            name='size',
        ),
        migrations.AddField(
            model_name='producttag',
            name='color',
            field=models.CharField(default='', max_length=265),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producttag',
            name='image',
            field=models.ImageField(default=True, upload_to='media'),
            preserve_default=False,
        ),
    ]
