# Generated by Django 2.0.1 on 2019-03-07 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping_app', '0008_auto_20190307_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttag',
            name='image',
        ),
    ]
