# Generated by Django 2.0.1 on 2019-03-08 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping_app', '0009_remove_producttag_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttag',
            name='color',
        ),
    ]
