# Generated by Django 2.0.1 on 2019-03-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping_app', '0010_remove_producttag_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttag',
            name='color',
            field=models.CharField(default=True, max_length=265),
            preserve_default=False,
        ),
    ]
