# Generated by Django 2.0.1 on 2019-03-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping_app', '0011_producttag_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttag',
            name='image',
            field=models.ImageField(default=True, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producttag',
            name='size',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
