# Generated by Django 2.0.1 on 2019-03-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping_app', '0012_auto_20190308_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttag',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='image',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='price',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='size',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='url',
            field=models.URLField(max_length=50),
        ),
    ]
