# Generated by Django 2.0.1 on 2019-03-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping_app', '0013_auto_20190308_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttag',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
