# Generated by Django 2.0.1 on 2019-03-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping_app', '0014_auto_20190308_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttag',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
