# Generated by Django 2.0.1 on 2019-03-09 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping_app', '0015_auto_20190308_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttag',
            name='color',
        ),
    ]
