# Generated by Django 2.0.1 on 2019-03-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping_app', '0016_remove_producttag_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttag',
            name='color',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
    ]
