# Generated by Django 2.0.1 on 2019-03-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping_app', '0019_auto_20190311_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='tag_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
